BillingsCoderDojo/Controllers/SignInReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BillingsCoderDojo.Models;
using BillingsCoderDojo.ViewModels;
using Microsoft.AspNet.Identity;

namespace BillingsCoderDojo.Controllers
{
    public class SignInReportController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: SignInReport
        [Authorize(Roles = "Mentors")]
        public ActionResult Index()
        {
            var signInSheet = from signIns in db.SignInModels
                              join users in db.Users on signIns.UserId equals users.Id
                              orderby signIns.LogTime descending
                              select new SignInReportViewModel
                              {
                                  Username = users.UserName,
                                  SignInTime = signIns.LogTime
                              };

            var signInSheetList = signInSheet.ToList().Select(s => 
                new SignInReportViewModel
                {
                    Username = s.Username, 
                    SignInTime = TimeZoneInfo.ConvertTimeFromUtc( TimeZoneInfo.ConvertTimeToUtc(s.SignInTime), TimeZoneInfo.FindSystemTimeZoneById("Mountain Standard Time"))
                });

            return View(signInSheetList);
        }

        // POST: SignInReport
        [Authorize(Roles = "Mentors")]
        [HttpPost]
        public ActionResult Index(string dateFilter)
        {
            var dateMin = Convert.ToDateTime(dateFilter);
            var dateMax = dateMin.AddDays(1);

            var signInSheet = from signIns in db.SignInModels
                              join users in db.Users on signIns.UserId equals users.Id
                              where signIns.LogTime > dateMin && signIns.LogTime < dateMax
                              orderby signIns.LogTime descending
                              select new SignInReportViewModel
                              {
                                  Username = users.UserName,
                                  SignInTime = signIns.LogTime
                              };

            return View(signInSheet.ToList());
        }
    }
}

BillingsCoderDojo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Billings Dojo!</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/bundles/jquery-ui-css")

    <script type="text/javascript">
        var appInsights=window.appInsights||function(config){
            function s(config){t[config]=function(){var i=arguments;t.queue.push(function(){t[config].apply(t,i)})}}var t={config:config},r=document,f=window,e="script",o=r.createElement(e),i,u;for(o.src=config.url||"//az416426.vo.msecnd.net/scripts/a/ai.0.js",r.getElementsByTagName(e)[0].parentNode.appendChild(o),t.cookie=r.cookie,t.queue=[],i=["Event","Exception","Metric","PageView","Trace"];i.length;)s("track"+i.pop());return config.disableExceptionTracking||(i="onerror",s("_"+i),u=f[i],f[i]=function(config,r,f,e,o){var s=u&&u(config,r,f,e,o);return s!==!0&&t["_"+i](config,r,f,e,o),s}),t
        }({
            instrumentationKey:"83646b13-81ed-42c2-997a-63dbaa67315c"
        });
        
        window.appInsights=appInsights;
        appInsights.trackPageView();
    </script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Billings Coder Dojo", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink( "Sign In", "Index", "SignIn" )</li>
                    @if (User.IsInRole("Mentors"))
                    {
                        <li>@Html.ActionLink("Sign In Report", "Index", "SignInReport")</li>
                    }
                    @*<li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Billings CoderDojo</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jquery-ui")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>